version: "3"
services:
    db:
        image: "microsoft/mssql-server-linux"
        environment:
          SA_PASSWORD: "Your_password123"
          ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"

    identity:
        build: ./Malikah.Identity
        ports:
            - "5000:80"
        depends_on:
            - db
            
    api:
        build: ./Malikah.Api
        ports:
            - "5003:80"
        depends_on:
            - mysqldb
            - identity
    admin:
        build: ./Malikah
        ports:
            - "5002:80"
        depends_on:
            - mysqldb
            - identity

    store:
        build: ./Malikah.Store
        ports:
            - "8080:80"
        depends_on:
            - mysqldb
            - identity
        volumes:
            - ./Malikah.Store:/var/www

    mysqldb:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: BimAyu1221!
        ports:
            - "3306:3306"